#
# Pantry Backend
#

openapi: '3.0.3'

info:
  description: Pantry Backend
  version: 0.1.0
  title: Pantry Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /dummy:
    get:
      description: Dummy Endpoint
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DummyResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /signup:
    get:
      description: Get all suers
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsrItem'
          
        default:
          description: Unexpected Error
          content:
            applcation/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'

    post:
      description: Creates a new account
      requestBody:
        description: Account to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        201:
          description: Successfully created account 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewUser'
        409:
          description: Email already in use
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'

  /foodlist:
    get: 
      description: Get all items
      responses:
        200:
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FoodItem'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'
    post:
      description: Add a food item to list
      requestBody:
        description: Food item to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        201:
          description: Successfully added account 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewUser'
        409:
          description: Food already there
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnexpectedError'

components:
  schemas:
    Error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message

    DummyResponse:
      properties:
        message:
          type: string
      required:
        - message
    UnexpectedError:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    
    NewUser:
      type: object
      properties:
        name:
            type: string
        email:
            type: string
            format: email
            # https://regexpattern.com/email-address/
            pattern: ^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
        password:
          type: string

    UsrItem:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
          # https://regexpattern.com/email-address/
          pattern: ^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
        password:
          type: string
          
    FoodItem:
      type: object
      properties:
        name:
          type: string
    NewFoodItem:
      type: object
      properties:
        name:
          type: string

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes