/* eslint-disable */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Myjato (https://sketchfab.com/Myjato)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fridge-stylized-gameready-f57bb579c5da4b9c95f1cb874ec558f7
title: Fridge / Stylized / gameready
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/assets/fridge.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/fridge.gltf')